@startuml Cinema
!theme bluegray
left to right direction

package "Sistema de Controle de Cinema" {
    actor "Cliente" as Cliente
    actor "Funcionário" as Funcionario

    rectangle "Operações" {
        usecase "Registrar Sala" as RegistrarSala
        usecase "Registrar Filme" as RegistrarFilme
        usecase "Criar Sessão" as CriarSessao
        usecase "Comprar Ingresso" as ComprarIngresso
    }

    Cliente -left-- ComprarIngresso
    Funcionario -- RegistrarSala
    Funcionario -- RegistrarFilme
    Funcionario -- CriarSessao
    RegistrarSala -- CriarSessao : <<extend>>
    RegistrarFilme -- CriarSessao : <<extend>>
    CriarSessao -- ComprarIngresso : <<extend>>
}
@enduml