@startuml Extensao2
' !theme bluegray 
left to right direction

skinparam defaultFontSize 30

actor "Cliente" as Cliente
actor "Funcionário" as Funcionario


usecase EncerrarConta as "Encerrar Conta.
--
extesion Points:
Saldo Negativo
Saldo Positivo"
usecase "Realizar Saque" as (RealizarSaque)
usecase "Realizar Depósito" as (RealizarDeposito)


note "{Se o Saldo for positivo}" as N1
note "{Se o Saldo for Negativo}" as N2


:Cliente: -- EncerrarConta
:Funcionario: -- EncerrarConta

EncerrarConta <|.. N1
N1 .. RealizarSaque: <<extend>>

EncerrarConta <|.. N2
N2 .. RealizarDeposito: <<extend>>

@enduml