@startuml
package "Computador" {
  class "CPU" {
    + execute()
  }

  class "Memória" {
    + read()
    + write()
  }

  class "DiscoRigido" {
    + read()
    + write()
  }
}

class "ComputadorPessoal" {
  + cpu : CPU
  + memória : Memória
  + discoRigido : "Disco Rigido"
}

ComputadorPessoal *-- "1" CPU : contém
ComputadorPessoal *-- "1" Memória : contém
ComputadorPessoal *-- "1" DiscoRigido : contém


@enduml
