@startuml
class Paciente {
    + nome : String
    + idade : Integer
    + historicoMedico : String
}

    class "Usuario" <<Stereotype>> {
        nome : String
        endereco : String
    }

    class "Emprestimo" <<Stereotype>> {
        dataEmprestimo : Date
        dataDevolucao : Date
    }

    Usuario -- Emprestimo : Realiza >
    Emprestimo -- Livro : Contem >
}
hide Livro circle
hide Usuario circle
hide Emprestimo circle
@enduml