@startuml

package "<<Profile>> Biblioteca" {
    left to right direction
    class "Livro" <<Stereotype>> {
        titulo : String
        autor : String
    }

    class "Usuario" <<Stereotype>> {
        nome : String
        endereco : String
    }

    class "Emprestimo" <<Stereotype>> {
        dataEmprestimo : Date
        dataDevolucao : Date
    }

    Usuario -- Emprestimo : Realiza >
    Emprestimo -- Livro : Contem >
}
hide Livro circle
hide Usuario circle
hide Emprestimo circle
@enduml