@startuml DiagramaUML
    !theme bluegray
    rectangle "UML" as UML
    rectangle "Diagramas Estruturais" as DiagramasEstruturais
    rectangle "Diagramas Compotamentais" as DiagramaCompotamental
    rectangle "Diagrama de Classes" as DiagramaClasses
    rectangle "Diagrama de Objetos" as DiagramaObjetos
    rectangle "Diagrama de Componentes" as DiagramaComponentes
    rectangle "Diagrama de Instalação" as DiagramaInstalacao
    rectangle "Diagrama de Distribuição" as DiagramaDistribuicao
    rectangle "Diagrama de Casos de Uso" as DiagramaCasosUso
    rectangle "Diagrama de Sequência" as DiagramaSequencia
    rectangle "Diagrama de Colaboração" as DiagramaColaboracao
    rectangle "Diagrama de Estados" as DiagramaEstados
    rectangle "Diagrama de Atividades" as DiagramaAtividades
    rectangle "Diagrama de Componentes" as DiagramaComponentes
    rectangle "Diagrama de Objetos" as DiagramaObjetos
    rectangle "Diagrama de Pacotes" as DiagramaPacotes
    rectangle "Diagrama de Perfil" as DiagramaPerfil

    rectangle "Idiomas" as Idiomas
    rectangle "Certificações" as Certificacoes

UML --> DiagramasEstruturais
UML --> DiagramaCompotamental
DiagramaCompotamental --> DiagramaClasses
DiagramaEstrutural --> DiagramaClasses
DiagramaEstrutural --> DiagramaObjetos
DiagramaEstrutural --> DiagramaComponentes
DiagramaEstrutural --> DiagramaInstalacao
DiagramaEstrutural --> DiagramaDistribuicao
DiagramaCompotamental --> DiagramaCasosUso
DiagramaCompotamental --> DiagramaSequencia
DiagramaCompotamental --> DiagramaColaboracao
DiagramaCompotamental --> DiagramaEstados
DiagramaCompotamental --> DiagramaAtividades
DiagramaCompotamental --> DiagramaComponentes
DiagramaCompotamental --> DiagramaObjetos
DiagramaCompotamental --> DiagramaPacotes
DiagramaCompotamental --> DiagramaPerfis


@enduml
