@startuml ProcessoPedido
!theme bluegray
start
:Cliente faz pedido;
if (Pedido aprovado?) then (sim)
    :Entrega pedido;
    stop
else (não)
    :Informa cliente sobre falha no pedido;
    stop
endif
@enduml

@startuml
(*) --> "Solicitação da Reserva"
--> "Pagamento"
--> "Emissão do Bilhete"
--> (*)
@enduml
