@startuml SistemaPedidos
!theme bluegray
actor Cliente
actor Funcionario

left to right direction
rectangle "Sistema de Pedidos" {
    usecase "Fazer Pedido" as UC1
    usecase "Pagar Pedido" as UC2
    usecase "Receber Pedido" as UC3
    usecase "Verificar Estoque" as UC4
    usecase "Emitir Nota Fiscal" as UC5
    
}

Cliente --> UC1 
Cliente --> UC2 
UC2 --> Funcionario 
UC1 <-- "Funcionario" 
UC4 <-- "Funcionario" 
UC5 <-- "Funcionario" 
Cliente --> UC3 


UC1 ..> UC4 : <<include>>
UC3 ..> UC5 : <<extend>>

@enduml


@startuml Biblioteca
!theme bluegray
actor "Usuário" as Usuario
actor "Bibliotecário" as Bibliotecario

left to right direction
rectangle "Sistema de Gerenciamento de Biblioteca" {
    usecase "Buscar Livros" as UC1
    usecase "Verificar Disponibilidade" as UC2
    usecase "Solicitar Empréstimo" as UC3
    usecase "Devolver Livro" as UC4
    usecase "Adicionar Livro" as UC5
    usecase "Remover Livro" as UC6
}

Usuario --> UC1
Usuario --> UC2
Usuario --> UC3
Usuario --> UC4
Bibliotecario -up-> UC5
Bibliotecario -up-> UC6

@enduml

