@startuml
skinparam classAttributeIconSize 0


' Associação Unária ou Reflexiva
class Employee {
    - name: String
    - supervisor: Employee
}

Employee "1" -- "0..1" Employee : supervisor

' Associação Binária
class Estudante {
    - nome: String
    - matricula: String
}

Estudante "0..*" -left- "1..*" Turma

' Associação Ternária

class Professor {
    - sobrenome: String
    - idade: int
    - disciplina: String
}

class Turma {
    - codigo: String
    - semestre: String
    - numeroDeAlunos: int
}

class SalaDeAula {
    - localizacao: String
    - capacidade: int
}

' (Student, Course) .. Enrollment

<> diamond


diamond -left-- "leciona *..1" Professor
diamond -down- "utiliza *..1" SalaDeAula
diamond --right-- "possui *..1 " Turma


@enduml
