@startuml ProcessoPedido
[*] --> NovoPedido
NovoPedido --> PedidoAprovado : Aprovação do Pedido
PedidoAprovado --> PedidoEntregue : Entrega do Pedido
PedidoAprovado --> PedidoCancelado : Cancelamento do Pedido
PedidoEntregue --> [*]
PedidoCancelado --> [*]
@enduml