@startuml tempo
robust "Cliente" as C
concise "Sistema" as S

@0
C is Ocioso
S is Ocioso

@+5
C -> S: Faz Pedido
C is Aguardando
S is Processando

@+10
S --> C: Confirma Pedido
C is Sastifeito
S is Ocioso
@enduml


