@startuml ControleAcesso
!theme bluegray
group sd enter senha
    participant Usuario
    participant Acesso
    activate Usuario
    Usuario -> Acesso: Entrar com a Senha
    activate Acesso
    Acesso -> Acesso: Veriricar Senha
    Acesso --> Usuario
  
end


@enduml

@startuml
partition sd Controle de Acesso {
  start 
  :sd enter senha;  
    if () then (Senha Correta)
      partition sd frame {
      :Liberar porta para uma ação;
      }
    else (Senha Incorreta)
      
    endif
    stop
}

@enduml