@startuml

box Diagrama Entrar com a Senha #White
    participant Usuario
    participant Acesso
    activate Usuario
    Usuario -> Acesso: Entrar com a Senha
    activate Acesso
    Acesso -> Acesso: Veriricar Senha
    Acesso --> Usuario
  
end box


@enduml

@startuml
partition sd Controle de Acesso {
  start
  partition sd enter senha {
    :Diagrama Entrar com a Senha;
      }
    if () then (Senha Correta)
      partition sd frame {
      :Liberar porta para uma ação;
      }
    else (Senha Incorreta)
      
    endif
    stop
}

@enduml